url: "http://simonduff.net"
github_base: "https://github.com/sduff/sduff.github.io/blob/master/"
date_format: "%b %-d, %Y"
google_analytics: 
markdown: kramdown
highlighter: rouge
exclude: ["_docs/template"]

collections:
  docs:
    output: true
    layout: default
    permalink: /:path
