title: "Simon Duff - Big Data Expert"
description: "Big Data Expert, Simon Duff, documents techniques and ideas for a variety of use-cases"
url: "http://simonduff.net"
github_base: "https://github.com/sduff/sduff.github.io/blob/master/"
date_format: "%b %-d, %Y"
google_analytics: 
markdown: kramdown
highlighter: rouge
exclude: ["_docs/template", vendor]

collections:
  docs:
    output: true
    layout: default
    permalink: /:path
