name: website

on:
  push:
    branches:
    - main
  schedule:
  - cron: '13 0 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout website builder
        uses: actions/checkout@v2
        with:
          repository: sduff/waste
          path: waste

      -
        name: Build website builder docker image
        run:  |
          cd waste
          docker build . --file Dockerfile --tag waste

      -
        name: Checkout website configuration
        uses: actions/checkout@v2

      -
        name: Run website builder
        run:  docker run -v /home/runner/work/sduff.github.io/sduff.github.io/src:/src -v /home/runner/work/sduff.github.io/sduff.github.io/templates:/templates -v /home/runner/work/sduff.github.io/sduff.github.io/static:/static -v /home/runner/work/sduff.github.io/sduff.github.io/build:/build  waste

#      -
#        name: Deploy to GitHub Pages
#        if: success()
#        uses: crazy-max/ghaction-github-pages@v2
#        with:
#          target_branch: gh-pages
#          build_dir: build
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
